# Generated by Django 2.2.14 on 2021-01-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0002_auto_20210123_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='onlinestore/images'),
        ),
    ]
